sudo: false
dist: xenial
language: python

env:
  - SH=bash

python:
  - "3.5"
  - "3.6"
  - "3.7"

cache:
  pip: true

install:
  - "pip install -r tests/requirements.txt"

script:
  - coverage run tests/tests.py

before_install:
  pip install codecov

after_success:
  codecov
